import Head from 'next/head'
import Image from 'next/image'
import Hero from './../components/Hero';
import Nav from './../components/Nav';
import Services from './../components/Services';





export default function Home() {
  return (
    <div className='bg-black  overflow-hidden  ' >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Nav />
        <Hero />
        <Services />
        
      </main>
    </div>
  )
}
